---
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: alertmanager
  namespace: mondane
spec:
  replicas: 1
  alertmanagerConfigSelector:
    matchLabels:
      mondane.org/watch: "true"
  alertmanagerConfigNamespaceSelector:
    matchLabels:
      mondane.org/watch: "true"
