---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mondane
  namespace: mondane-ui
spec:
  commonName: mondane.org
  dnsNames:
    - mondane.org
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: selfsigned
  privateKey:
    algorithm: RSA
    rotationPolicy: Always
    size: 4096
  secretName: mondane-certificate
  subject:
    countries:
    - DE
    localities:
    - Osnabrück
    provinces:
    - Niedersachsen
